### ISSUE TITLE
Not Passing frameSize to MediaRecorder start Function

### ISSUE THREAD

**Issue by Sed9yDataBank** [Flam3rboy/puppeteer-stream#75]
@Flam3rboy 👋 why are you passing a `timeslice` here https://github.com/Flam3rboy/puppeteer-stream/blob/10ea8e918119f01f5d7028b77d082c963ab2b342/extension/background.js#L70 ? Here as well https://github.com/Flam3rboy/puppeteer-stream/blob/10ea8e918119f01f5d7028b77d082c963ab2b342/src/PuppeteerStream.ts#L143 Is there a particular reason? 

Not having a `timeslice` can let the UA optimize the way it handles collecting data into the blobs, by saving the data in a blob in the disk instead of memory. It also simplifies the code since there's no need for a blob array or the bookkeeping that comes with it.

**Comment by Flam3rboy** [comment]
Because else the browser would not continuously stream the blobs and instead would create one big blob after the recording is finished.
However, this package needs a continuous stream for live streaming the puppeteer browser window for the specified usage (e.g. being able to live stream what puppeteer does).

**Comment by Flam3rboy** [comment]
If you don't need live streaming, you could add PR with a option to not pass the frameSize

**Comment by Sed9yDataBank** [comment]
@Flam3rboy thanks for explaining 🥇 I will look into opening a PR containing the changes for a review as you said.
